export const HoldingsAbi = [
  {
    inputs: [
      {
        internalType: "contract IHubRegistry",
        name: "hubRegistry_",
        type: "address",
      },
      { internalType: "address", name: "deployer", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AlreadyInitialized", type: "error" },
  { inputs: [], name: "HoldingNotFound", type: "error" },
  { inputs: [], name: "MulDiv_Overflow", type: "error" },
  { inputs: [], name: "NotAuthorized", type: "error" },
  { inputs: [], name: "Uint128_Overflow", type: "error" },
  { inputs: [], name: "WrongAssetId", type: "error" },
  { inputs: [], name: "WrongShareClassId", type: "error" },
  { inputs: [], name: "WrongValuation", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "assetId",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "D18",
        name: "pricePoolPerAsset",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "amount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "decreasedValue",
        type: "uint128",
      },
    ],
    name: "Decrease",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
    ],
    name: "Deny",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "assetId",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "D18",
        name: "pricePoolPerAsset",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "amount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "increasedValue",
        type: "uint128",
      },
    ],
    name: "Increase",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "assetId",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "contract IERC7726",
        name: "valuation",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isLiability",
        type: "bool",
      },
      {
        components: [
          { internalType: "AccountId", name: "accountId", type: "uint32" },
          { internalType: "uint8", name: "kind", type: "uint8" },
        ],
        indexed: false,
        internalType: "struct HoldingAccount[]",
        name: "accounts",
        type: "tuple[]",
      },
    ],
    name: "Initialize",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
    ],
    name: "Rely",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "assetId",
        type: "uint128",
      },
      { indexed: false, internalType: "uint8", name: "kind", type: "uint8" },
      {
        indexed: false,
        internalType: "AccountId",
        name: "accountId",
        type: "uint32",
      },
    ],
    name: "SetAccountId",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "assetId",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isPositive",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "diffValue",
        type: "uint128",
      },
    ],
    name: "Update",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "assetId",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "contract IERC7726",
        name: "valuation",
        type: "address",
      },
    ],
    name: "UpdateValuation",
    type: "event",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "", type: "uint64" },
      { internalType: "ShareClassId", name: "", type: "bytes16" },
      { internalType: "AssetId", name: "", type: "uint128" },
      { internalType: "uint8", name: "kind", type: "uint8" },
    ],
    name: "accountId",
    outputs: [{ internalType: "AccountId", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
    ],
    name: "amount",
    outputs: [{ internalType: "uint128", name: "amount_", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "D18", name: "pricePoolPerAsset", type: "uint128" },
      { internalType: "uint128", name: "amount_", type: "uint128" },
    ],
    name: "decrease",
    outputs: [
      { internalType: "uint128", name: "amountValue", type: "uint128" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "deny",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "", type: "uint64" },
      { internalType: "ShareClassId", name: "", type: "bytes16" },
      { internalType: "AssetId", name: "", type: "uint128" },
    ],
    name: "holding",
    outputs: [
      { internalType: "uint128", name: "assetAmount", type: "uint128" },
      { internalType: "uint128", name: "assetAmountValue", type: "uint128" },
      { internalType: "contract IERC7726", name: "valuation", type: "address" },
      { internalType: "bool", name: "isLiability", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "hubRegistry",
    outputs: [
      { internalType: "contract IHubRegistry", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "D18", name: "pricePoolPerAsset", type: "uint128" },
      { internalType: "uint128", name: "amount_", type: "uint128" },
    ],
    name: "increase",
    outputs: [
      { internalType: "uint128", name: "amountValue", type: "uint128" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      {
        internalType: "contract IERC7726",
        name: "valuation_",
        type: "address",
      },
      { internalType: "bool", name: "isLiability_", type: "bool" },
      {
        components: [
          { internalType: "AccountId", name: "accountId", type: "uint32" },
          { internalType: "uint8", name: "kind", type: "uint8" },
        ],
        internalType: "struct HoldingAccount[]",
        name: "accounts",
        type: "tuple[]",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
    ],
    name: "isInitialized",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
    ],
    name: "isLiability",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "rely",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "uint8", name: "kind", type: "uint8" },
      { internalType: "AccountId", name: "accountId_", type: "uint32" },
    ],
    name: "setAccountId",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
    ],
    name: "update",
    outputs: [
      { internalType: "bool", name: "isPositive", type: "bool" },
      { internalType: "uint128", name: "diffValue", type: "uint128" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      {
        internalType: "contract IERC7726",
        name: "valuation_",
        type: "address",
      },
    ],
    name: "updateValuation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
    ],
    name: "valuation",
    outputs: [{ internalType: "contract IERC7726", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
    ],
    name: "value",
    outputs: [{ internalType: "uint128", name: "value_", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "wards",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
