export const HubRegistryAbi = [
  {
    inputs: [{ internalType: "address", name: "deployer", type: "address" }],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AssetAlreadyRegistered", type: "error" },
  { inputs: [], name: "AssetNotFound", type: "error" },
  { inputs: [], name: "EmptyAccount", type: "error" },
  { inputs: [], name: "EmptyCurrency", type: "error" },
  { inputs: [], name: "EmptyShareClassManager", type: "error" },
  {
    inputs: [{ internalType: "PoolId", name: "id", type: "uint64" }],
    name: "NonExistingPool",
    type: "error",
  },
  { inputs: [], name: "NotAuthorized", type: "error" },
  { inputs: [], name: "PoolAlreadyRegistered", type: "error" },
  { inputs: [], name: "Uint128_Overflow", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
    ],
    name: "Deny",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "AssetId",
        name: "assetId",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "decimals",
        type: "uint8",
      },
    ],
    name: "NewAsset",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "PoolId",
        name: "poolId",
        type: "uint64",
      },
      {
        indexed: true,
        internalType: "address",
        name: "manager",
        type: "address",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "currency",
        type: "uint128",
      },
    ],
    name: "NewPool",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
    ],
    name: "Rely",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: false,
        internalType: "bytes",
        name: "metadata",
        type: "bytes",
      },
    ],
    name: "SetMetadata",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: false,
        internalType: "AssetId",
        name: "currency",
        type: "uint128",
      },
    ],
    name: "UpdateCurrency",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "what", type: "bytes32" },
      {
        indexed: false,
        internalType: "address",
        name: "dependency",
        type: "address",
      },
    ],
    name: "UpdateDependency",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "address",
        name: "manager",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "canManage", type: "bool" },
    ],
    name: "UpdateManager",
    type: "event",
  },
  {
    inputs: [{ internalType: "PoolId", name: "", type: "uint64" }],
    name: "currency",
    outputs: [{ internalType: "AssetId", name: "", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "AssetId", name: "assetId", type: "uint128" }],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "decimals_", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "asset_", type: "uint256" }],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "decimals_", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "PoolId", name: "poolId_", type: "uint64" }],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "decimals_", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "deny",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "dependency",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "PoolId", name: "poolId_", type: "uint64" }],
    name: "exists",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "AssetId", name: "assetId", type: "uint128" }],
    name: "isRegistered",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "", type: "uint64" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "manager",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "PoolId", name: "", type: "uint64" }],
    name: "metadata",
    outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "uint48", name: "postfix", type: "uint48" },
    ],
    name: "poolId",
    outputs: [{ internalType: "PoolId", name: "poolId_", type: "uint64" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "uint8", name: "decimals_", type: "uint8" },
    ],
    name: "registerAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId_", type: "uint64" },
      { internalType: "address", name: "manager_", type: "address" },
      { internalType: "AssetId", name: "currency_", type: "uint128" },
    ],
    name: "registerPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "rely",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId_", type: "uint64" },
      { internalType: "bytes", name: "metadata_", type: "bytes" },
    ],
    name: "setMetadata",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId_", type: "uint64" },
      { internalType: "AssetId", name: "currency_", type: "uint128" },
    ],
    name: "updateCurrency",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "what", type: "bytes32" },
      { internalType: "address", name: "dependency_", type: "address" },
    ],
    name: "updateDependency",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId_", type: "uint64" },
      { internalType: "address", name: "manager_", type: "address" },
      { internalType: "bool", name: "canManage", type: "bool" },
    ],
    name: "updateManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "wards",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
