export const MessageDispatcherAbi = [
  {
    inputs: [
      { internalType: "uint16", name: "localCentrifugeId_", type: "uint16" },
      { internalType: "contract IRoot", name: "root_", type: "address" },
      { internalType: "contract IGateway", name: "gateway_", type: "address" },
      {
        internalType: "contract ITokenRecoverer",
        name: "tokenRecoverer_",
        type: "address",
      },
      { internalType: "address", name: "deployer", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "FileUnrecognizedParam", type: "error" },
  { inputs: [], name: "NotAuthorized", type: "error" },
  { inputs: [], name: "SliceOutOfBounds", type: "error" },
  { inputs: [], name: "SliceOverflow", type: "error" },
  { inputs: [], name: "Uint64_Overflow", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
    ],
    name: "Deny",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "what", type: "bytes32" },
      {
        indexed: false,
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "File",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
    ],
    name: "Rely",
    type: "event",
  },
  {
    inputs: [],
    name: "balanceSheet",
    outputs: [
      {
        internalType: "contract IBalanceSheetGatewayHandler",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "deny",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "what", type: "bytes32" },
      { internalType: "address", name: "data", type: "address" },
    ],
    name: "file",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "gateway",
    outputs: [{ internalType: "contract IGateway", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "hub",
    outputs: [
      {
        internalType: "contract IHubGatewayHandler",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "investmentManager",
    outputs: [
      {
        internalType: "contract IRequestManagerGatewayHandler",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "localCentrifugeId",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "rely",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "root",
    outputs: [{ internalType: "contract IRoot", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "uint128", name: "assetAmount", type: "uint128" },
      { internalType: "D18", name: "pricePoolPerAsset", type: "uint128" },
    ],
    name: "sendApprovedDeposits",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
    ],
    name: "sendCancelDepositRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
    ],
    name: "sendCancelRedeemRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "bytes32", name: "target", type: "bytes32" },
    ],
    name: "sendCancelUpgrade",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "sendDepositRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "bytes32", name: "receiver", type: "bytes32" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "sendExecuteTransferShares",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      {
        internalType: "uint128",
        name: "fulfilledAssetAmount",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "fulfilledShareAmount",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "cancelledAssetAmount",
        type: "uint128",
      },
    ],
    name: "sendFulfilledDepositRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      {
        internalType: "uint128",
        name: "fulfilledAssetAmount",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "fulfilledShareAmount",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "cancelledShareAmount",
        type: "uint128",
      },
    ],
    name: "sendFulfilledRedeemRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "targetCentrifugeId", type: "uint16" },
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "bytes32", name: "receiver", type: "bytes32" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "sendInitiateTransferShares",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "uint128", name: "shareAmount", type: "uint128" },
      { internalType: "D18", name: "pricePoolPerShare", type: "uint128" },
    ],
    name: "sendIssuedShares",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "uint64", name: "maxPriceAge", type: "uint64" },
    ],
    name: "sendMaxAssetPriceAge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "uint64", name: "maxPriceAge", type: "uint64" },
    ],
    name: "sendMaxSharePriceAge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "PoolId", name: "poolId", type: "uint64" },
    ],
    name: "sendNotifyPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "D18", name: "price", type: "uint128" },
    ],
    name: "sendNotifyPricePoolPerAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "chainId", type: "uint16" },
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "D18", name: "sharePrice", type: "uint128" },
    ],
    name: "sendNotifyPricePoolPerShare",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "uint8", name: "decimals", type: "uint8" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
      { internalType: "bytes32", name: "hook", type: "bytes32" },
    ],
    name: "sendNotifyShareClass",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
    ],
    name: "sendNotifyShareMetadata",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "bytes32", name: "target", type: "bytes32" },
      { internalType: "bytes32", name: "token", type: "bytes32" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "bytes32", name: "to", type: "bytes32" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "sendRecoverTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "sendRedeemRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "uint8", name: "decimals", type: "uint8" },
    ],
    name: "sendRegisterAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "uint128", name: "assetAmount", type: "uint128" },
      { internalType: "uint128", name: "shareAmount", type: "uint128" },
      { internalType: "D18", name: "pricePoolPerShare", type: "uint128" },
    ],
    name: "sendRevokedShares",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "bytes32", name: "target", type: "bytes32" },
    ],
    name: "sendScheduleUpgrade",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "bool", name: "enabled", type: "bool" },
    ],
    name: "sendSetQueue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "bytes32", name: "who", type: "bytes32" },
      { internalType: "bool", name: "canManage", type: "bool" },
    ],
    name: "sendUpdateBalanceSheetManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "bytes32", name: "target", type: "bytes32" },
      { internalType: "bytes", name: "payload", type: "bytes" },
    ],
    name: "sendUpdateContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "uint128", name: "amount", type: "uint128" },
      { internalType: "D18", name: "pricePoolPerAsset", type: "uint128" },
      { internalType: "bool", name: "isIncrease", type: "bool" },
      { internalType: "bool", name: "isSnapshot", type: "bool" },
      { internalType: "uint64", name: "nonce", type: "uint64" },
    ],
    name: "sendUpdateHoldingAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "bytes", name: "payload", type: "bytes" },
    ],
    name: "sendUpdateRestriction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "centrifugeId", type: "uint16" },
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "bytes32", name: "hook", type: "bytes32" },
    ],
    name: "sendUpdateShareHook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "uint128", name: "shares", type: "uint128" },
      { internalType: "bool", name: "isIssuance", type: "bool" },
      { internalType: "bool", name: "isSnapshot", type: "bool" },
      { internalType: "uint64", name: "nonce", type: "uint64" },
    ],
    name: "sendUpdateShares",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "bytes32", name: "vaultOrFactory", type: "bytes32" },
      { internalType: "enum VaultUpdateKind", name: "kind", type: "uint8" },
    ],
    name: "sendUpdateVault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "spoke",
    outputs: [
      {
        internalType: "contract ISpokeGatewayHandler",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tokenRecoverer",
    outputs: [
      { internalType: "contract ITokenRecoverer", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "wards",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
