export const PoolManagerAbi = [
  {
    inputs: [
      { internalType: "address", name: "escrow_", type: "address" },
      { internalType: "address", name: "tokenFactory_", type: "address" },
      { internalType: "address[]", name: "vaultFactories", type: "address[]" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "NoCode", type: "error" },
  { inputs: [], name: "NotAuthorized", type: "error" },
  { inputs: [], name: "SafeTransferFailed", type: "error" },
  { inputs: [], name: "UnknownMessageType", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "poolId", type: "uint64" },
    ],
    name: "AddPool",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "bytes16",
        name: "trancheId",
        type: "bytes16",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "AddShareClass",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
    ],
    name: "Deny",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "bytes16",
        name: "trancheId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "factory",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "vault",
        type: "address",
      },
    ],
    name: "DeployVault",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "what", type: "bytes32" },
      {
        indexed: false,
        internalType: "address",
        name: "data",
        type: "address",
      },
    ],
    name: "File",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "what", type: "bytes32" },
      {
        indexed: false,
        internalType: "address",
        name: "factory",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "status", type: "bool" },
    ],
    name: "File",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "bytes16",
        name: "trancheId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "vault",
        type: "address",
      },
    ],
    name: "LinkVault",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "bytes16",
        name: "trancheId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "computedAt",
        type: "uint64",
      },
    ],
    name: "PriceUpdate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "assetId",
        type: "uint128",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      { indexed: false, internalType: "string", name: "name", type: "string" },
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "decimals",
        type: "uint8",
      },
    ],
    name: "RegisterAsset",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
    ],
    name: "Rely",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "bytes16",
        name: "trancheId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "destinationId",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "destinationAddress",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "amount",
        type: "uint128",
      },
    ],
    name: "TransferTrancheTokens",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "bytes16",
        name: "trancheId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "vault",
        type: "address",
      },
    ],
    name: "UnlinkVault",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "bytes16",
        name: "trancheId",
        type: "bytes16",
      },
      {
        indexed: false,
        internalType: "address",
        name: "target",
        type: "address",
      },
      { indexed: false, internalType: "bytes", name: "payload", type: "bytes" },
    ],
    name: "UpdateContract",
    type: "event",
  },
  {
    inputs: [{ internalType: "uint64", name: "poolId", type: "uint64" }],
    name: "addPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "uint8", name: "decimals", type: "uint8" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
      { internalType: "address", name: "hook", type: "address" },
    ],
    name: "addShareClass",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "assetToId",
    outputs: [{ internalType: "uint128", name: "assetId", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "balanceSheetManager",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "checkedAssetToId",
    outputs: [{ internalType: "uint128", name: "assetId", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint128", name: "assetId", type: "uint128" }],
    name: "checkedIdToAsset",
    outputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
    ],
    name: "checkedToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "deny",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
      { internalType: "uint128", name: "assetId", type: "uint128" },
      { internalType: "address", name: "factory", type: "address" },
    ],
    name: "deployVault",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "escrow",
    outputs: [{ internalType: "contract IEscrow", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "what", type: "bytes32" },
      { internalType: "address", name: "factory", type: "address" },
      { internalType: "bool", name: "status", type: "bool" },
    ],
    name: "file",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "what", type: "bytes32" },
      { internalType: "address", name: "data", type: "address" },
    ],
    name: "file",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
      { internalType: "address", name: "destinationAddress", type: "address" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "handleTransferTrancheTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint128", name: "assetId", type: "uint128" }],
    name: "idToAsset",
    outputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "", type: "uint64" },
      { internalType: "bytes16", name: "", type: "bytes16" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "vault", type: "address" },
    ],
    name: "isLinked",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "poolId", type: "uint64" }],
    name: "isPoolActive",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
      { internalType: "uint128", name: "assetId", type: "uint128" },
      { internalType: "address", name: "vault", type: "address" },
    ],
    name: "linkVault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "poolId", type: "uint64" }],
    name: "pools",
    outputs: [{ internalType: "uint256", name: "createdAt", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token_", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "recoverTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "uint16", name: "destChainId", type: "uint16" },
    ],
    name: "registerAsset",
    outputs: [{ internalType: "uint128", name: "assetId", type: "uint128" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "rely",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "sender",
    outputs: [
      {
        internalType: "contract IVaultMessageSender",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
      { internalType: "uint128", name: "assetId", type: "uint128" },
    ],
    name: "sharePrice",
    outputs: [
      { internalType: "uint128", name: "price", type: "uint128" },
      { internalType: "uint64", name: "computedAt", type: "uint64" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
    ],
    name: "token",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tokenFactory",
    outputs: [
      { internalType: "contract ITokenFactory", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
      { internalType: "uint16", name: "destinationId", type: "uint16" },
      { internalType: "bytes32", name: "recipient", type: "bytes32" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "transferShares",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
      { internalType: "uint128", name: "assetId", type: "uint128" },
      { internalType: "address", name: "vault", type: "address" },
    ],
    name: "unlinkVault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
      { internalType: "bytes", name: "payload", type: "bytes" },
    ],
    name: "update",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
      { internalType: "address", name: "target", type: "address" },
      { internalType: "bytes", name: "update_", type: "bytes" },
    ],
    name: "updateContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
      { internalType: "bytes", name: "update_", type: "bytes" },
    ],
    name: "updateRestriction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
    ],
    name: "updateShareMetadata",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
      { internalType: "uint128", name: "assetId", type: "uint128" },
      { internalType: "uint128", name: "price", type: "uint128" },
      { internalType: "uint64", name: "computedAt", type: "uint64" },
    ],
    name: "updateSharePrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "poolId", type: "uint64" },
      { internalType: "bytes16", name: "scId", type: "bytes16" },
      { internalType: "address", name: "hook", type: "address" },
    ],
    name: "updateTrancheHook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "vault", type: "address" }],
    name: "vaultDetails",
    outputs: [
      {
        components: [
          { internalType: "uint128", name: "assetId", type: "uint128" },
          { internalType: "address", name: "asset", type: "address" },
          { internalType: "uint256", name: "tokenId", type: "uint256" },
          { internalType: "bool", name: "isWrapper", type: "bool" },
          { internalType: "bool", name: "isLinked", type: "bool" },
        ],
        internalType: "struct VaultDetails",
        name: "details",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "factory", type: "address" }],
    name: "vaultFactory",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "wards",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
