export const ShareClassManagerAbi = [
  {
    inputs: [
      {
        internalType: "contract IHubRegistry",
        name: "hubRegistry_",
        type: "address",
      },
      { internalType: "address", name: "deployer", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AlreadyIssued", type: "error" },
  { inputs: [], name: "AlreadyUsedSalt", type: "error" },
  { inputs: [], name: "ApprovalRequired", type: "error" },
  { inputs: [], name: "CancellationQueued", type: "error" },
  { inputs: [], name: "DecreaseMoreThanIssued", type: "error" },
  { inputs: [], name: "EpochNotFound", type: "error" },
  {
    inputs: [
      { internalType: "uint32", name: "providedEpoch", type: "uint32" },
      { internalType: "uint32", name: "nowEpoch", type: "uint32" },
    ],
    name: "EpochNotInSequence",
    type: "error",
  },
  { inputs: [], name: "InsufficientPending", type: "error" },
  { inputs: [], name: "InvalidMetadataName", type: "error" },
  { inputs: [], name: "InvalidMetadataSize", type: "error" },
  { inputs: [], name: "InvalidMetadataSymbol", type: "error" },
  { inputs: [], name: "InvalidSalt", type: "error" },
  { inputs: [], name: "IssuanceRequired", type: "error" },
  { inputs: [], name: "MulDiv_Overflow", type: "error" },
  { inputs: [], name: "NoOrderFound", type: "error" },
  { inputs: [], name: "NotAuthorized", type: "error" },
  { inputs: [], name: "PoolMissing", type: "error" },
  { inputs: [], name: "RevocationRequired", type: "error" },
  { inputs: [], name: "RevokeMoreThanIssued", type: "error" },
  { inputs: [], name: "ShareClassNotFound", type: "error" },
  { inputs: [], name: "Uint128_Overflow", type: "error" },
  { inputs: [], name: "Uint64_Overflow", type: "error" },
  { inputs: [], name: "ZeroApprovalAmount", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      { indexed: true, internalType: "uint32", name: "index", type: "uint32" },
      { indexed: false, internalType: "string", name: "name", type: "string" },
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
    ],
    name: "AddShareClass",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      { indexed: true, internalType: "uint32", name: "index", type: "uint32" },
    ],
    name: "AddShareClass",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "depositAssetId",
        type: "uint128",
      },
      { indexed: false, internalType: "uint32", name: "epoch", type: "uint32" },
      {
        indexed: false,
        internalType: "uint128",
        name: "approvedPoolAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "approvedAssetAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "pendingAssetAmount",
        type: "uint128",
      },
    ],
    name: "ApproveDeposits",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "payoutAssetId",
        type: "uint128",
      },
      { indexed: false, internalType: "uint32", name: "epoch", type: "uint32" },
      {
        indexed: false,
        internalType: "uint128",
        name: "approvedShareAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "pendingShareAmount",
        type: "uint128",
      },
    ],
    name: "ApproveRedeems",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      { indexed: false, internalType: "uint32", name: "epoch", type: "uint32" },
      {
        indexed: false,
        internalType: "bytes32",
        name: "investor",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "depositAssetId",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "paymentAssetAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "pendingAssetAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "claimedShareAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "issuedAt",
        type: "uint64",
      },
    ],
    name: "ClaimDeposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      { indexed: false, internalType: "uint32", name: "epoch", type: "uint32" },
      {
        indexed: false,
        internalType: "bytes32",
        name: "investor",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "payoutAssetId",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "paymentShareAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "pendingShareAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "claimedAssetAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "revokedAt",
        type: "uint64",
      },
    ],
    name: "ClaimRedeem",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
    ],
    name: "Deny",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "depositAssetId",
        type: "uint128",
      },
      { indexed: false, internalType: "uint32", name: "epoch", type: "uint32" },
      {
        indexed: false,
        internalType: "D18",
        name: "navPoolPerShare",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "D18",
        name: "navAssetPerShare",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "issuedShareAmount",
        type: "uint128",
      },
    ],
    name: "IssueShares",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
    ],
    name: "Rely",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "issuedShareAmount",
        type: "uint128",
      },
    ],
    name: "RemoteIssueShares",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "revokedAssetAmount",
        type: "uint128",
      },
    ],
    name: "RemoteRevokeShares",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "payoutAssetId",
        type: "uint128",
      },
      { indexed: false, internalType: "uint32", name: "epoch", type: "uint32" },
      {
        indexed: false,
        internalType: "D18",
        name: "navPoolPerShare",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "D18",
        name: "navAssetPerShare",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "revokedShareAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "revokedAssetAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "revokedPoolAmount",
        type: "uint128",
      },
    ],
    name: "RevokeShares",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "depositAssetId",
        type: "uint128",
      },
      { indexed: false, internalType: "uint32", name: "epoch", type: "uint32" },
      {
        indexed: false,
        internalType: "bytes32",
        name: "investor",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "pendingUserAssetAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "pendingTotalAssetAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "queuedUserAssetAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "pendingCancellation",
        type: "bool",
      },
    ],
    name: "UpdateDepositRequest",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      { indexed: false, internalType: "string", name: "name", type: "string" },
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
    ],
    name: "UpdateMetadata",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: true,
        internalType: "AssetId",
        name: "payoutAssetId",
        type: "uint128",
      },
      { indexed: false, internalType: "uint32", name: "epoch", type: "uint32" },
      {
        indexed: false,
        internalType: "bytes32",
        name: "investor",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "pendingUserShareAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "pendingTotalShareAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "queuedUserShareAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "pendingCancellation",
        type: "bool",
      },
    ],
    name: "UpdateRedeemRequest",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "PoolId", name: "poolId", type: "uint64" },
      {
        indexed: true,
        internalType: "ShareClassId",
        name: "scId",
        type: "bytes16",
      },
      {
        indexed: false,
        internalType: "D18",
        name: "navPoolPerShare",
        type: "uint128",
      },
    ],
    name: "UpdateShareClass",
    type: "event",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
    ],
    name: "addShareClass",
    outputs: [{ internalType: "ShareClassId", name: "scId_", type: "bytes16" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "AssetId", name: "depositAssetId", type: "uint128" },
      { internalType: "uint32", name: "nowDepositEpochId", type: "uint32" },
      { internalType: "uint128", name: "approvedAssetAmount", type: "uint128" },
      { internalType: "D18", name: "pricePoolPerAsset", type: "uint128" },
    ],
    name: "approveDeposits",
    outputs: [
      { internalType: "uint128", name: "pendingAssetAmount", type: "uint128" },
      { internalType: "uint128", name: "approvedPoolAmount", type: "uint128" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "AssetId", name: "payoutAssetId", type: "uint128" },
      { internalType: "uint32", name: "nowRedeemEpochId", type: "uint32" },
      { internalType: "uint128", name: "approvedShareAmount", type: "uint128" },
      { internalType: "D18", name: "pricePoolPerAsset", type: "uint128" },
    ],
    name: "approveRedeems",
    outputs: [
      { internalType: "uint128", name: "pendingShareAmount", type: "uint128" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      { internalType: "AssetId", name: "depositAssetId", type: "uint128" },
    ],
    name: "cancelDepositRequest",
    outputs: [
      {
        internalType: "uint128",
        name: "cancelledAssetAmount",
        type: "uint128",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      { internalType: "AssetId", name: "payoutAssetId", type: "uint128" },
    ],
    name: "cancelRedeemRequest",
    outputs: [
      {
        internalType: "uint128",
        name: "cancelledShareAmount",
        type: "uint128",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      { internalType: "AssetId", name: "depositAssetId", type: "uint128" },
    ],
    name: "claimDeposit",
    outputs: [
      { internalType: "uint128", name: "payoutShareAmount", type: "uint128" },
      { internalType: "uint128", name: "paymentAssetAmount", type: "uint128" },
      {
        internalType: "uint128",
        name: "cancelledAssetAmount",
        type: "uint128",
      },
      { internalType: "bool", name: "canClaimAgain", type: "bool" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      { internalType: "AssetId", name: "payoutAssetId", type: "uint128" },
    ],
    name: "claimRedeem",
    outputs: [
      { internalType: "uint128", name: "payoutAssetAmount", type: "uint128" },
      { internalType: "uint128", name: "paymentShareAmount", type: "uint128" },
      {
        internalType: "uint128",
        name: "cancelledShareAmount",
        type: "uint128",
      },
      { internalType: "bool", name: "canClaimAgain", type: "bool" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "decreaseShareClassIssuance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "deny",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "depositAssetId", type: "uint128" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
    ],
    name: "depositRequest",
    outputs: [
      { internalType: "uint128", name: "pending", type: "uint128" },
      { internalType: "uint32", name: "lastUpdate", type: "uint32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
    ],
    name: "epochId",
    outputs: [
      { internalType: "uint32", name: "deposit", type: "uint32" },
      { internalType: "uint32", name: "redeem", type: "uint32" },
      { internalType: "uint32", name: "issue", type: "uint32" },
      { internalType: "uint32", name: "revoke", type: "uint32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "uint32", name: "epochId_", type: "uint32" },
    ],
    name: "epochInvestAmounts",
    outputs: [
      { internalType: "uint128", name: "pendingAssetAmount", type: "uint128" },
      { internalType: "uint128", name: "approvedAssetAmount", type: "uint128" },
      { internalType: "uint128", name: "approvedPoolAmount", type: "uint128" },
      { internalType: "D18", name: "pricePoolPerAsset", type: "uint128" },
      { internalType: "D18", name: "navPoolPerShare", type: "uint128" },
      { internalType: "uint64", name: "issuedAt", type: "uint64" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "assetId", type: "uint128" },
      { internalType: "uint32", name: "epochId_", type: "uint32" },
    ],
    name: "epochRedeemAmounts",
    outputs: [
      { internalType: "uint128", name: "pendingShareAmount", type: "uint128" },
      { internalType: "uint128", name: "approvedShareAmount", type: "uint128" },
      { internalType: "uint128", name: "payoutAssetAmount", type: "uint128" },
      { internalType: "D18", name: "pricePoolPerAsset", type: "uint128" },
      { internalType: "D18", name: "navPoolPerShare", type: "uint128" },
      { internalType: "uint64", name: "revokedAt", type: "uint64" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
    ],
    name: "exists",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "hubRegistry",
    outputs: [
      { internalType: "contract IHubRegistry", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "increaseShareClassIssuance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "AssetId", name: "depositAssetId", type: "uint128" },
      { internalType: "uint32", name: "nowIssueEpochId", type: "uint32" },
      { internalType: "D18", name: "navPoolPerShare", type: "uint128" },
    ],
    name: "issueShares",
    outputs: [
      { internalType: "uint128", name: "issuedShareAmount", type: "uint128" },
      { internalType: "uint128", name: "depositAssetAmount", type: "uint128" },
      { internalType: "uint128", name: "depositPoolAmount", type: "uint128" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      { internalType: "AssetId", name: "depositAssetId", type: "uint128" },
    ],
    name: "maxDepositClaims",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      { internalType: "AssetId", name: "payoutAssetId", type: "uint128" },
    ],
    name: "maxRedeemClaims",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "ShareClassId", name: "scId", type: "bytes16" }],
    name: "metadata",
    outputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "ShareClassId", name: "scId", type: "bytes16" }],
    name: "metrics",
    outputs: [
      { internalType: "uint128", name: "totalIssuance", type: "uint128" },
      { internalType: "D18", name: "navPerShare", type: "uint128" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "AssetId", name: "depositAssetId", type: "uint128" },
    ],
    name: "nowDepositEpoch",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "AssetId", name: "depositAssetId", type: "uint128" },
    ],
    name: "nowIssueEpoch",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "AssetId", name: "depositAssetId", type: "uint128" },
    ],
    name: "nowRedeemEpoch",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "AssetId", name: "depositAssetId", type: "uint128" },
    ],
    name: "nowRevokeEpoch",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "depositAssetId", type: "uint128" },
    ],
    name: "pendingDeposit",
    outputs: [{ internalType: "uint128", name: "pending", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "payoutAssetId", type: "uint128" },
    ],
    name: "pendingRedeem",
    outputs: [{ internalType: "uint128", name: "pending", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "PoolId", name: "poolId", type: "uint64" }],
    name: "previewNextShareClassId",
    outputs: [{ internalType: "ShareClassId", name: "scId", type: "bytes16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "uint32", name: "index", type: "uint32" },
    ],
    name: "previewShareClassId",
    outputs: [{ internalType: "ShareClassId", name: "scId", type: "bytes16" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "depositAssetId", type: "uint128" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
    ],
    name: "queuedDepositRequest",
    outputs: [
      { internalType: "bool", name: "isCancelling", type: "bool" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "payoutAssetId", type: "uint128" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
    ],
    name: "queuedRedeemRequest",
    outputs: [
      { internalType: "bool", name: "isCancelling", type: "bool" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "ShareClassId", name: "scId", type: "bytes16" },
      { internalType: "AssetId", name: "payoutAssetId", type: "uint128" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
    ],
    name: "redeemRequest",
    outputs: [
      { internalType: "uint128", name: "pending", type: "uint128" },
      { internalType: "uint32", name: "lastUpdate", type: "uint32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "rely",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "uint128", name: "amount", type: "uint128" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      { internalType: "AssetId", name: "depositAssetId", type: "uint128" },
    ],
    name: "requestDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "uint128", name: "amount", type: "uint128" },
      { internalType: "bytes32", name: "investor", type: "bytes32" },
      { internalType: "AssetId", name: "payoutAssetId", type: "uint128" },
    ],
    name: "requestRedeem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "AssetId", name: "payoutAssetId", type: "uint128" },
      { internalType: "uint32", name: "nowRevokeEpochId", type: "uint32" },
      { internalType: "D18", name: "navPoolPerShare", type: "uint128" },
    ],
    name: "revokeShares",
    outputs: [
      { internalType: "uint128", name: "revokedShareAmount", type: "uint128" },
      { internalType: "uint128", name: "payoutAssetAmount", type: "uint128" },
      { internalType: "uint128", name: "payoutPoolAmount", type: "uint128" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "salt", type: "bytes32" }],
    name: "salts",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "PoolId", name: "poolId", type: "uint64" }],
    name: "shareClassCount",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "", type: "bytes16" },
    ],
    name: "shareClassIds",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
    ],
    name: "updateMetadata",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "PoolId", name: "poolId", type: "uint64" },
      { internalType: "ShareClassId", name: "scId_", type: "bytes16" },
      { internalType: "D18", name: "navPoolPerShare", type: "uint128" },
    ],
    name: "updatePricePerShare",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "wards",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
